### ISSUE TITLE
3.0.0 installation error

### ISSUE THREAD

**Issue by dpo** [ampl/mp#93] opened 2016-03-25 15:21 UTC
On OSX 10.9, I get the following when building release 3.0.0:
```
CMake Error at doc/cmake_install.cmake:31 (file):
  file INSTALL cannot find
  "/tmp/asl20160325-1399-1bc5h1m/mp-3.0.0/doc/ampl.github.io".
Call Stack (most recent call first):
  cmake_install.cmake:60 (include)
```
This is at 100% of the build; everything else went well. In `doc/cmake_install.cmake`, there is
```
if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/doc/mp" TYPE DIRECTORY FILES "/tmp/asl20160325-1399-1bc5h1m/mp-3.0.0/doc/ampl.github.io/" REGEX "/\\.[^/]*$" EXCLUDE)
endif()
```

**Comment by vitaut** [comment] 2016-03-25 16:01
Have you run `make doc` before `make install`? I can make doc installation optional, but this will only apply to the next version.

**Comment by dpo** [comment] 2016-03-25 16:38
Sorry I didn't see that in the instructions. Now I have bigger problems:
```
cd /tmp/asl20160325-7775-l45v3b/mp-3.0.0/build/doc && python /tmp/asl20160325-7775-l45v3b/mp-3.0.0/support/build-docs.py
Traceback (most recent call last):
  File "/tmp/asl20160325-7775-l45v3b/mp-3.0.0/support/build-docs.py", line 147, in <module>
    build_docs('.')
  File "/tmp/asl20160325-7775-l45v3b/mp-3.0.0/support/build-docs.py", line 80, in build_docs
    create_virtualenv(os.path.join(workdir, 'build', 'virtualenv'))
  File "/tmp/asl20160325-7775-l45v3b/mp-3.0.0/support/build-docs.py", line 23, in create_virtualenv
    run('virtualenv', venv_dir)
  File "/tmp/asl20160325-7775-l45v3b/mp-3.0.0/support/build-docs.py", line 15, in run
    check_call(args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 537, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by vitaut** [comment] 2016-03-25 19:04
Documentation building script requires `virtualenv`. I've added a new section that clarifies this to README [here](https://github.com/ampl/mp#building-the-documentation). Also installing the docs is now optional: https://github.com/ampl/mp/commit/77b2db5708a2381cd8fe3327999a5be0d68b4f62

Thanks for catching this!

**Comment by dpo** [comment] 2016-03-25 19:57
Thanks. For the record, I *do* have `virtualenv`, but it's not picked up because CMake picks up system Python. I have `virtualenv` with Homebrew Python (which appears first on my `PATH`).

**Comment by vitaut** [comment] 2016-03-25 21:14
It's a bit weird that CMake doesn't pick up the first python executable on the `PATH`. I can add a call to 

```cmake
find_package(PythonInterp)
```

and use `PYTHON_EXECUTABLE` instead of just `python` if you like. This might solve the problem or at least give a way to specify which python to use.

**Comment by dpo** [comment] 2016-03-25 22:14
Personally, I'd rather leave Python out of the mix. What's the CMake option to deactivate building the docs?

**Comment by vitaut** [comment] 2016-03-25 22:22
The docs are not built by default. The problem is that in 3.0 they are included in installation. I don't think there is an option to control this, but you can apply this simple fix: https://github.com/ampl/mp/commit/77b2db5708a2381cd8fe3327999a5be0d68b4f62

**Comment by dpo** [comment] 2016-03-27 05:54
Thanks. With your simple fix, it builds. Unfortunately, #65 isn't in there.

**Comment by vitaut** [comment] 2016-03-27 14:47
Looks like #65 was submitted to branch 2.0, not master. Is there any reason for that and do you want me to merge it into master?

**Comment by dpo** [comment] 2016-03-27 15:51
Yes it would be great to have it in master. I assumed the 2.0 branch would be merged into master at some point.

**Comment by vitaut** [comment] 2016-03-28 17:50
I've cherry-picked the two commits from #65 into master and removed branch 2.0 to avoid confusion and since versions 2.x are no longer supported. If you want I can tag version 3.1 which will include the fixes discussed here.

**Comment by dpo** [comment] 2016-03-28 18:05
Many thanks @vitaut! It would be great to tag a new release, if you're ready.

**Comment by vitaut** [comment] 2016-03-29 16:09
Done: https://github.com/ampl/mp/releases/tag/3.1.0. Thanks again for reporting the issues.

**Comment by vitaut** [comment] 2016-03-30 18:33
I'm closing this issue, but feel free to reopen or open another one if there are any problems.

**Closed by vitaut** 2016-03-30 18:33 UTC
