### ISSUE TITLE
gjh only computes the Hessian of the objective, not the Hessian of the Lagrangian

### ISSUE THREAD

**Issue by baharev** [ampl/mp#77] opened 2016-01-29 00:53 UTC
Only the Hessian of the objective is computed unless I set the Lagrange multipliers explicitly. We are talking about the *structural* sparsity pattern; the actual values are irrelevant to me. All files are in https://github.com/baharev/Lagrangian_Hessian for reproducing the issue.

Execute: 

```
ampl model_X.mod 
ampl model_Y.mod 
diff model_X.mod model_Y.mod
```

to see the issue.

-----

Unfortunately, I need a workaround quickly. I have thousands of benchmarks and setting the dual variables explicitly as in `model_Y` is not an option. I would have to parse those models and that is out of the question. 

I tried assigning `_scon.dual` and,  `_scon.dinit` and `_scon.dinit0` but `ampl` says that they are not assignable suffixes.

Is there an easier way to set somehow them to `0` other than jamming a `d` segment into the .nl file myself? I can do this one but it is quite ugly. 

Any help is greatly appreciated.

**Comment by vitaut** [comment] 2016-01-29 01:32
I don't think you can assign duals using constraint aliases like `_scon`, only real constraint names. Possible workarounds are:

1. Allocate dual vector in `gjh` by adding something like

  ```c++
        else
          y = calloc(sizeof(double), m);
```

   before this line: https://github.com/ampl/mp/blob/master/src/asl/solvers/examples/gjh.c#L108

2. It's enough to set initial dual for at least one constraint so you can introduce a constraint just for this purpose, e.g.

  ```ampl
var z;
s.t. c := 0: z >= 0;
```
  and ignore it in the results.

**Comment by baharev** [comment] 2016-01-29 12:06
Option 1 works for me, thanks! I have totally missed that `gjh` is open source. 

Could you add that to the `gjh.c` source, please?

**Comment by vitaut** [comment] 2016-01-30 00:27
This is not a bug in `gjh`, but just an optimization. In the case of `model_X.mod` `Y` is null which is treated as all `Y[i]` zero in

![screenshot from 2016-01-29 16 16 21](https://cloud.githubusercontent.com/assets/576385/12691734/b9faf996-c6a3-11e5-89c1-8a31b991200e.png)

and `sphsetup` doesn't even allocate space for zero terms.

In the case of `model_Y.mod`, all the `Y[i]` are zero too, but `sphsetup` doesn't check that.

In the end the result is effectively the same:

```ampl
# model_X.gjh:
param :SH: HS :=
2	2	2
;
# model_Y.gjh:
param :SH: HS :=
1	1	0 # note zero here which could in fact be omitted
2	2	2
;
```

In any case `gjh` is just an example and if you are interested in some other behavior I recommend creating a custom version of it. If you are interested only in sparsity pattern rather than actual values, you might only need to call  `sphsetup`.

**Comment by baharev** [comment] 2016-01-30 12:04
According to the documentation, `SH` is supposed to give me the **structural** sparsity pattern, and exactly that happens with `model_Y`. That is the behavior I would consider the correct behavior.

Not the structural but the actual sparsity pattern is reported for `model_X`. That is not what the documentation of `gjh` says, it is not consistent with the behavior with `model_Y`, and it is confusing since all the optimization solvers I know of require the structural sparsity pattern. That saved allocation for the zero elements is not helping anybody. Just my 2 cents.

**Comment by vitaut** [comment] 2016-02-01 23:44
Are you referring to [README.gjh](https://github.com/ampl/mp/blob/master/src/asl/solvers/examples/README.gjh) or some other piece of documentation?

**Comment by baharev** [comment] 2016-02-02 12:01
Yes, in particular *"When "sparse" is specified, index sets SJ and SH of the structural
nonzeros also appear in the .gjh file"*. Note the *structural*.

Please don't "fix" it by removing the structural from README.gjh; please just add

```
      else
        y = calloc(sizeof(double), m);
```

to gjh.c (your Option 1) and then all is fine. Thanks!

**Comment by vitaut** [comment] 2016-02-03 18:37
I'm not the owner of this code, but I'll forward your suggestion and the proposed solution to David.

**Comment by baharev** [comment] 2016-02-03 19:31
OK, thanks!

**Comment by vitaut** [comment] 2016-02-16 17:47
Fixed in https://github.com/ampl/mp/commit/e397f518d9f797ea7eedf1582865dd79a2113950 in a simpler way (without allocating `y`).

**Comment by baharev** [comment] 2016-02-16 18:44
Thanks for the update! As long `gjh` behaves as one would expect from the docs, any solution is OK with me. :)

**Comment by vitaut** [comment] 2016-02-16 18:50
AFAICS it does now =):
```
$ ampl model_X.mod 
...
set SH := (1,1) (2,2);
```

**Closed by vitaut** 2016-02-16 18:50 UTC
