### ISSUE TITLE
gjh fails with a strange error message

### ISSUE THREAD

**Issue by baharev** [ampl/mp#73] opened 2016-01-25 00:15 UTC
I am running tests on the COCONUT Benchmarks and I get strange error messages from `gjh` in certain cases. In particular, these models are causing strange errors:

https://github.com/baharev/gjh_fails

I am running with:

AMPL Version 20160121 (Linux x86_64)
gjh (Linux x86_64), ASL(20150814)

and I get:

```
$ gjh lib1_etamac.nl
Error evaluating objective function: can't evaluate log(0).
$ gjh lib1_hhfair.nl 
Error evaluating objective function: can't evaluate pow'(0,0.944).
gjh lib1_pindyck.nl 
Error evaluating constraint 81: can't compute 250/0.
```

I have looked into the `x0` segment of the nl files and they seem to be correct. I do not understand why I get these error messages given the `x0`.

I hope I haven't looked over some trivial mistake on my side.

Any help is greatly appreciated.

**Comment by vitaut** [comment] 2016-01-25 15:34
Thanks for the bug report. The error occurs in gradient evaluation and, since the variables values are non-zero, this doesn't look right. Will look into it.

**Comment by vitaut** [comment] 2016-01-26 00:53
The problem is that ASL only works with .nl files written with the default value of `nl_permute`, quoting David Gay:

> The ASL assumes $nl_permute has its default
value when the .nl file is written.  All bets are off if one fiddles
with option nl_permute.  People who want to do so must supply their
own suitably adjusted ASL (and must link gjh against it).

**Comment by baharev** [comment] 2016-01-26 01:00
OK but could you issue at least a warning, please? The `nl_permute` is a documented option, and there was nothing warning me about this danger (or I missed it).

**Comment by baharev** [comment] 2016-01-26 12:46
**Please re-open this issue.** 

I have removed the `option nl_permute 0;` line and the situation got worse. The update models with the generated output are at https://github.com/baharev/gjh_fails.

The `lib1_etamac` instance fails as before, nothing has changed, and for the other two instances I get:

```
$ ampl lib1_hhfair.nl 

lib1_hhfair.nl, line 1 (offset 3):
        syntax error
context:  g7  >>> 0  <<< 2 0 25 20160121 0 1    # problem lib1_hhfair
$ ampl lib1_pindyck.nl

lib1_pindyck.nl, line 1 (offset 3):
        syntax error
context:  g7  >>> 0  <<< 2 0 96 20160121 0 1    # problem lib1_pindyck
```

Apart from this, if the users are not supposed to play with the otherwise documented `nl_permute` option, then ampl should issue a warning saying something like *"Warning: non-default nl_permute value detected, make sure you have a suitably adjusted ASL!"* in my opinion.

Please make sure before closing a bug report next time that the proposed solution actually solves the problem.

**Comment by baharev** [comment] 2016-01-26 14:13
Same results with `gjh (Linux x86_64), ASL(20151209)`.

**Comment by baharev** [comment] 2016-01-26 14:22
There was a typo in the previous comment, sorry about that. Please see the updated comment.

**Comment by vitaut** [comment] 2016-01-26 20:22
Are you sure that the .nl files in your GitHub repo were generated with the default value for `nl_permute`?

```
> ampl lib1_etamac.mod
...
> ./gjh lib1_etamac.nl
gjh: "lib1_etamac.gjh" written.  Execute

	include "lib1_etamac.gjh"
	remove "lib1_etamac.gjh";
> ./gjh -v
gjh (Linux x86_64), ASL(20151209)
```

Comparing `lib1_etamac.nl` to https://github.com/baharev/gjh_fails/blob/master/lib1_etamac.nl, I see that the one in your repo is different (in constraint order) which suggests that the latter was not generated with the default `nl_permute`.

Issuing a warning seems reasonable, I'll see what can be done.

P.S. I did test that using the default `nl_permute` fixes the issue before closing it.

**Comment by baharev** [comment] 2016-01-26 20:39
Please check, I did this a minute ago:

https://github.com/baharev/gjh_fails/blob/master/session.txt

I don't see my mistake and there is no `nl_permute` in the mod files.

**Comment by baharev** [comment] 2016-01-26 20:44
Wait, I have an `OPTIONS_IN` in my bash `.profile`. Probably that is the culprit, I have to check it.

**Comment by vitaut** [comment] 2016-01-26 20:46
Just wanted to suggest that you need to check environment variables.

**Comment by baharev** [comment] 2016-01-26 21:04
OK, it was my fault: I have totally forgotten about the `OPTIONS_IN` in my bash `.profile`. Sorry. I have re-run everything and this issue seems to be resolved for those 3 mod files in the repo.

However, please wait before closing it: I have altogether 52 failing cases and I would like to check that none of these failures are due to this issue. These are messy benchmark models failing for whatever reason (I have found invalid models, etc.). It will take a while but this has high priority for me.

**Comment by vitaut** [comment] 2016-01-26 21:09
No problems. Glad that cleared up a bit. I am looking into the possibility of adding a warning for the case when an .nl file was generated with unsupported `nl_permute` value, so I plan to keep this issue open anyway until that's resolved.

**Comment by baharev** [comment] 2016-01-26 23:47
OK, this issue seems to be re-solved. Now I "only" have 12 failures and none of them is due to this issue. 

As for me, a warning would have been helpful that I am about to generate a non-default .nl file (either because explicitly setting the `nl_permute` in the model file or because of the environment variables) *and* that requires a suitably adjusted ASL on the solver's side.

I apologize for the false alarm, and many thanks for your help!

**Comment by vitaut** [comment] 2016-02-12 00:12
AMPL now gives a warning about `nl_permute` that may cause problems with solvers:

> 20160211

> Adjust debugging option nl_permute so when permutations are suppressed, the .nl file will indicate numbers of nonlinear constraints and variables based on the last nonlinear constraint or variable. Give a Caution message when suppressing permutations affects the .nl file. The "8" and "16" bits of $nl_permute can suppress these new Cautions. $nl_permute is now the sum of
     1 → reorder constraints
     2 → reorder variables
     4 → reorder objectives
     8 → suppress Caution about constraints
    16 → suppress Caution about variables.
The default value for $nl_permute remains 3. Option nl_permute is not meant for use with solvers; great confusion may arise if binary or integer variables are present. Most users should avoid fiddling with $nl_permute.

For example:

```
> ampl lib1_etamac.mod
...
	Caution: Using option nl_permute to suppress permutations
of constraints and variables may cause trouble for some solvers.
```

**Comment by baharev** [comment] 2016-02-12 19:20
Great, thanks! The issue is solved as far as I am concerned.

**Comment by vitaut** [comment] 2016-02-12 19:24
Thanks for reporting.

**Closed** 2016-02-12 19:23 UTC
